# Generated by Django 4.2.25 on 2025-11-29 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Policy name or identifier', max_length=255)),
                ('document', models.FileField(upload_to='policies/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('insurance_type', models.CharField(blank=True, choices=[('LIFE', 'Life Insurance'), ('HEALTH', 'Health Insurance')], max_length=20, null=True)),
                ('policy_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('insurer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('last_processed', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Policies',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyNominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('allocation_percentage', models.DecimalField(decimal_places=2, default=100.0, help_text='Percentage of sum assured allocated to this nominee', max_digits=5)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='policies.policy')),
            ],
            options={
                'ordering': ['-allocation_percentage'],
            },
        ),
        migrations.CreateModel(
            name='PolicyExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='policies.policy')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PolicyBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_type', models.CharField(choices=[('BASE', 'Base Coverage'), ('RIDER', 'Rider'), ('ADDON', 'Add-on'), ('BONUS', 'Bonus')], default='BASE', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('coverage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='policies.policy')),
            ],
            options={
                'ordering': ['benefit_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HealthInsuranceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual'), ('FAMILY', 'Family Floater'), ('SENIOR_CITIZEN', 'Senior Citizen')], max_length=50, null=True)),
                ('room_rent_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('co_payment_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('network_hospitals_count', models.IntegerField(blank=True, null=True)),
                ('cashless_facility', models.BooleanField(default=True)),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_details', to='policies.policy')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('extraction_timestamp', models.DateTimeField(auto_now_add=True)),
                ('extraction_model', models.CharField(default='gemini-pro', max_length=100)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_document', to='policies.policy')),
            ],
        ),
        migrations.CreateModel(
            name='CoveredMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('pre_existing_conditions', models.TextField(blank=True, null=True)),
                ('health_insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='covered_members', to='policies.healthinsurancedetails')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_assured', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('premium_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('premium_frequency', models.CharField(blank=True, choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half Yearly'), ('YEARLY', 'Yearly')], max_length=20, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coverage', to='policies.policy')),
            ],
            options={
                'indexes': [models.Index(fields=['end_date'], name='policies_po_end_dat_94053d_idx'), models.Index(fields=['start_date'], name='policies_po_start_d_1c3718_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['user', 'insurance_type'], name='policies_po_user_id_49b87a_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['user', 'is_active'], name='policies_po_user_id_cbb89e_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['policy_number'], name='policies_po_policy__a03f9f_idx'),
        ),
    ]
