# Generated by Django 4.2.25 on 2025-11-29 19:32

from django.db import migrations, models
import policies.models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='document',
            field=models.FileField(storage=policies.models.get_policy_storage, upload_to=''),
        ),
    ]
