# Generated by Django 4.2.25 on 2025-12-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_alter_policy_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='ai_extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='ai_extraction_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='ai_extraction_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='policy',
            name='is_verified_by_user',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
