# Generated by Django 4.2.25 on 2025-12-11 08:27

from django.db import migrations, models
import nomisafe_backend.storages


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_policy_ai_extracted_at_policy_ai_extraction_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policycoverage',
            name='maturity_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount payable on maturity (guaranteed returns)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='document',
            field=models.FileField(storage=nomisafe_backend.storages.PolicyDocumentStorage(), upload_to=''),
        ),
    ]
