# Generated by Django 4.2.25 on 2026-02-14 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_policycoverage_maturity_amount_alter_policy_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='insurance_type',
            field=models.CharField(blank=True, choices=[('LIFE', 'Life Insurance'), ('HEALTH', 'Health Insurance'), ('MOTOR', 'Motor Insurance')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='MotorInsuranceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(blank=True, choices=[('TWO_WHEELER', 'Two Wheeler'), ('FOUR_WHEELER', 'Four Wheeler'), ('COMMERCIAL', 'Commercial Vehicle')], max_length=20, null=True)),
                ('policy_type', models.CharField(blank=True, choices=[('COMPREHENSIVE', 'Comprehensive'), ('THIRD_PARTY', 'Third Party'), ('STANDALONE_OD', 'Standalone Own Damage')], max_length=20, null=True)),
                ('vehicle_make', models.CharField(blank=True, help_text='e.g., Maruti, Honda, Hyundai', max_length=100, null=True)),
                ('vehicle_model', models.CharField(blank=True, help_text='e.g., Swift, City, i20', max_length=100, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True)),
                ('engine_number', models.CharField(blank=True, max_length=50, null=True)),
                ('chassis_number', models.CharField(blank=True, max_length=50, null=True)),
                ('year_of_manufacture', models.IntegerField(blank=True, null=True)),
                ('idv', models.DecimalField(blank=True, decimal_places=2, help_text='Insured Declared Value', max_digits=10, null=True)),
                ('own_damage_cover', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('third_party_cover', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ncb_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='No Claim Bonus percentage', max_digits=5, null=True)),
                ('previous_policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('has_zero_depreciation', models.BooleanField(default=False)),
                ('has_engine_protection', models.BooleanField(default=False)),
                ('has_roadside_assistance', models.BooleanField(default=False)),
                ('policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motor_details', to='policies.policy')),
            ],
        ),
    ]
