# Generated by Django 4.2.25 on 2026-02-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0005_alter_policy_insurance_type_motorinsurancedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coveredmember',
            name='relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
