# Generated by Django 4.2.25 on 2026-02-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0006_alter_coveredmember_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinsurancedetails',
            name='cashless_facility',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
