# Generated by Django 4.2.25 on 2026-02-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0007_alter_healthinsurancedetails_cashless_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='tutorial_thumbnails/')),
                ('youtube_url', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display (lowest first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tutorial',
                'verbose_name_plural': 'Tutorials',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='How we secure your family future', max_length=255)),
                ('subtitle', models.TextField(default="Securely track assets, policies, and investments to protect your family's future.")),
                ('youtube_url', models.URLField(help_text='YouTube video URL for the home screen', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Configuration',
                'verbose_name_plural': 'Video Configuration',
            },
        ),
    ]
