# Generated by Django 4.2.25 on 2026-02-15 14:02

from django.db import migrations, models
import nomisafe_backend.storages


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0008_tutorial_videoconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='thumbnail',
            field=models.ImageField(storage=nomisafe_backend.storages.TutorialThumbnailStorage(), upload_to=''),
        ),
    ]
