# Generated by Django 4.2.25 on 2025-11-09 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_aadhaar_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AadhaarVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_reference', models.CharField(max_length=64)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('aadhaar_last_4', models.CharField(max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aadhaar_verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aadhaar Verification',
                'verbose_name_plural': 'Aadhaar Verifications',
            },
        ),
        migrations.CreateModel(
            name='AadhaarOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('otp_reference', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aadhaar_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aadhaar OTP',
                'verbose_name_plural': 'Aadhaar OTPs',
            },
        ),
    ]
