# Generated by Django 4.2.25 on 2025-11-17 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_aadhaar_verified_aadhaarverification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aadhaarverification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_aadhaar_verified',
        ),
        migrations.DeleteModel(
            name='AadhaarOTP',
        ),
        migrations.DeleteModel(
            name='AadhaarVerification',
        ),
    ]
