# Generated by Django 4.2.25 on 2025-11-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_aadhaar_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_aadhaar_verified',
            field=models.BooleanField(default=False),
        ),
    ]
