# Generated by Django 4.2.25 on 2025-11-28 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_is_aadhaar_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Policy',
        ),
    ]
