# Generated by Django 4.2.25 on 2025-12-11 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address_district',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_pincode',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address_state',
        ),
    ]
