# Generated by Django 4.2.25 on 2026-02-15 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nomisafe_backend.storages


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_userprofile_address_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppNominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_details', models.CharField(blank=True, max_length=255, null=True)),
                ('id_proof_type', models.CharField(blank=True, max_length=100, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=16, null=True)),
                ('id_proof_file', models.FileField(blank=True, null=True, storage=nomisafe_backend.storages.AppNomineeDocumentStorage(), upload_to='nominees/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_nominee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'App Nominee',
                'verbose_name_plural': 'App Nominees',
            },
        ),
    ]
