# Generated by Django 4.2.25 on 2026-02-15 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nomisafe_backend.storages


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_appnominee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document', models.FileField(storage=nomisafe_backend.storages.PropertyDocumentStorage(), upload_to='properties/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
