# Generated by Django 4.2.25 on 2026-02-15 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nomisafe_backend.storages


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appnominee',
            name='id_proof_file',
            field=models.FileField(blank=True, null=True, storage=nomisafe_backend.storages.AppNomineeDocumentStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='document',
            field=models.FileField(storage=nomisafe_backend.storages.PropertyDocumentStorage(), upload_to=''),
        ),
        migrations.CreateModel(
            name='FirstConnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_connects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
